### ISSUE TITLE
Does maximum system capacity with disks alone has changed with new GCP 64TB disks?

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/cloud-volumes-ontap#130]
Page: [Supported configurations for Cloud Volumes ONTAP 9.8 in GCP](https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_configs_gcp_98.html)

With the introduction of new 64TB disk size support, one may expect that 256TB (Maximum system capacity with disks alone) limit may have been removed up to 368TB (license limit).

Are this limit still in place even using 64TB disks or do we need to update the docs?
(If the limit still stays, may need to reword the explanation)

Regards,

**Comment by netapp-bcammett** [comment]
Hi Gabriel,

Thank you for your feedback. The limit is still the same because it's dictated by GCP virtual machine limits. 

I've noted this on the the storage limits page:
https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_limits_gcp_98.html#disk-and-tiering-limits

And on the Cloud Manager what's new page where the change was introduced:
https://docs.netapp.com/us-en/occm/reference_new_occm.html#cloud-volumes-ontap-enhancements

Thanks again for your feedback.

Regards,
Ben

**Comment by gabrieltokyo** [comment]
Good work Ben, thank you.
