### ISSUE TITLE
The table of supported nodes is not visible for ONTAP 9.8 at AWS 

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/cloud-volumes-ontap#137]
Page: [Supported configurations for Cloud Volumes ONTAP 9.8 in AWS](https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_configs_aws_98.html)

Hi, we used to show the list of AWS nodes supported here but looks like the table is not visible currently.
Refer to previous version:
https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_configs_aws_97.html#supported-configurations-by-license

Could we have the list back again?

Cheers

**Comment by netapp-bcammett** [comment]
Hi Gabriel,

Thanks for reaching out. By "AWS nodes" do you mean the supported EC2 instance types? If yes, that information is still on the page, but it was broken out in order to provide more details about what each instance type provides:

https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_configs_aws_98.html#supported-compute

Thanks,
Ben

**Comment by gabrieltokyo** [comment]
Hi Ben,
Yes I was referring to EC2 supported instances.
Now I understand, we put all compute info in same one table and left the storage supported by license as before.

Thank you,
Gabriel
