### ISSUE TITLE
Can we state the 100 TB FlexVol limit?

### ISSUE THREAD

**Issue by randobrando46** [NetAppDocs/cloud-volumes-ontap#146]
Page: [Storage limits for Cloud Volumes ONTAP 9.8 in AWS](https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_limits_aws_98.html)

Hardware Universe says the largest FlexVol for the largest platforms is 100 TB.  Can this be stated as a max with a caveat that there are also hardware dependencies?  It's challenging to search so much to find what seems to be a known limitation.  Seems like having this in the more commonly used documentation would be a good thing.

**Comment by netapp-bcammett** [comment]
Hello,

Thank your for reaching out. While Cloud Volumes ONTAP can support 100 TB volumes on some configurations, it can't on others because of aggregate limits. Your comment appears to be about AWS where the raw capacity limit for an aggregate is 96 TB. That's why the limits state that the max limit is dependent on the size of the aggregate.

For other configurations like Google Cloud where the max aggregate capacity is 256 TB, we do list that the max volume size is 100 TB.

Please let me know if that explanation helps.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
Hey there,

Just wanted to follow up to see if the explanation that I provided helps explain why we've documented the limit the way that we have.

Thanks,
Ben
